In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]

In [5]:
a = np.array(a, int)
a

array([1, 2, 3, 4, 5])

In [7]:
test_array = np.array(["1", "4", 5.0, 8], float)
test_array

array([1., 4., 5., 8.])

In [9]:
type(test_array)

numpy.ndarray

In [11]:
type(test_array[3])

numpy.float64

In [13]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]
a[0] is b[-1]

True

In [15]:
a = np.array(a)
b = np.array(b)
a[0] is b[-1]

False

In [17]:
test_array.dtype

dtype('float64')

In [18]:
a = [[1,2,3], [4,5,6], [4,5,6]]

In [20]:
np.array(a).shape

(3, 3)

In [23]:
vector = [1,2,3,4]
np.array(vector, int).shape

(4,)

In [25]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix,int).shape

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [28]:
tensor = [
    [[1,2,5,8], [1,2,5,8], [1,2,5,8]],
    [[1,2,5,8], [1,2,5,8], [1,2,5,8]],
    [[1,2,5,8], [1,2,5,8], [1,2,5,8]],
    [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
]
np.array(tensor, int).shape

(4, 3, 4)

In [29]:
np.array(tensor, int).ndim

3

In [31]:
np.array(tensor, int).size

48